### ISSUE TITLE
Button with input focus sometimes appears bold after switching tabs

### ISSUE THREAD

**Issue by grokys** [PolymerElements/paper-button#29] opened 2015-06-24 09:25 UTC
In Chrome 43, sometimes after clicking a button then changing tabs in Chrome or changing to a different application, the button will appear bold until clicked again. This can be seen on the demo page.

**Comment by kungufli** [comment] 2015-07-14 10:32
This bug was already reported in the past (https://github.com/PolymerElements/paper-button/issues/24), and is still present in the latest 1.0.3 version of the element. Also, it affects (at least) paper-icon-button, paper-checkbox, paper-radio-button and paper-splider too. @notwaldorf @cdata Any news on this?

**Comment by ilin-t** [comment] 2015-08-04 13:56
The bug still exists. I tried with disabling and then enabling the button after the on-click method is finished but it still did not work. It is also happening on when browsing the apps from smartphones and tablets. Is there any feedback from google, or maybe you have some suggestion how to temporarily fix this ?

**Comment by notwaldorf** [comment] 2015-08-04 18:56
The problem is that this behaviour isn't entirely incorrect. After clicking the button, it stays focused (this is also true of native buttons). When you switch to a different tab, and then back to the original one, the button is styled as if it's focused, which it technically is.

Here's a demo of the native HTML button doing this as well: http://output.jsbin.com/bijukuqofo

/@cdata for input/to tell me i'm wrong :)

**Comment by motss** [comment] 2015-08-22 12:50
can try to eliminate the bold font by explicitly setting the font-weight of the focused `paper-button` to normal

**Comment by joshheinrichs** [comment] 2015-08-25 22:06
You can add this CSS to get rid of the bold:
```CSS
paper-button::shadow .keyboard-focus {
	font-weight: normal;
}
```

**Comment by cdata** [comment] 2015-10-19 22:40
Closing this as a dupe of #24.

**Closed by cdata** 2015-10-19 22:40 UTC
