### ISSUE TITLE
paper-button in paper-toolbar doesn't work on IE10

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-button#57] opened 2015-09-28 14:16 UTC
`paper-button` inside a `paper-toolbar` doesn't work correctly on IE10.

Example code:
```
<html>
  <head>
    <script src="../bower_components/webcomponentsjs/webcomponents.min.js"></script>  
    <link rel="import" href="../bower_components/iron-icons/iron-icons.html">
    <link rel="import" href="../bower_components/paper-button/paper-button.html">
    <link rel="import" href="../bower_components/paper-toolbar/paper-toolbar.html">
  </head>
  <body class="fullbleed">
    <paper-toolbar>
      <paper-button id="button" icon="menu"></paper-button>
    </paper-toolbar>

    <script>
      window.addEventListener('WebComponentsReady', function(e) {
        document.querySelector('#button').addEventListener('click',
          function(e) {
            console.log("button pressed");
          });
      });
    </script>
  </body>
</html>
```

The same issue is present for `paper-icon-button` inside a `paper-toolbar` (see https://github.com/PolymerElements/paper-icon-button/issues/39).

**Comment by kungufli** [comment] 2015-09-28 14:20
Seems caused by a bug on `paper-toolbar` https://github.com/PolymerElements/paper-toolbar/issues/30.

**Comment by cdata** [comment] 2015-10-19 21:17
@kungufli Thanks for confirming that this is caused by a bug elsewhere. I'm gonna close this issue so that we don't have duplicate reports.

**Closed by cdata** 2015-10-19 21:17 UTC
