### ISSUE TITLE
paper-button in IE is bold for un-focused and regular width for focused

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/paper-button#64] opened 2015-10-20 15:59 UTC
Left: IE 11.0.10240.16431 is left
Right: Chrome 46.0.2490.71 m (64-bit)
Both on Windows 10.

![paper-button](https://cloud.githubusercontent.com/assets/2515209/10613098/60313256-7719-11e5-8186-cac4c78af639.png)

**Comment by L-u-k-e** [comment] 2015-10-25 22:48
I have the same issue on IE 11. I'm on Windows 7. 

Checking the console reveals that the buttons are incorrectly receiving the `.keyboard-focus` class by default. 

My guess is that a call to `toggle()` somewhere turns it off when it actually gets focused.

**Comment by L-u-k-e** [comment] 2015-10-25 23:25
I did some logging in `iron-button-behavior.html` and the focus state is being correctly defaulted to `false`. 

The issue is in `paper-button-behavior.html`:

    observers: [
      '_calculateElevation(focused, disabled, active, pressed, receivedFocusFromKeyboard)',
      '_computeKeyboardClass(receivedFocusFromKeyboard)'
    ],
    ...
     _computeKeyboardClass: function(receivedFocusFromKeyboard) {
      this.classList.toggle('keyboard-focus', receivedFocusFromKeyboard);
    },

The observer relies on `this.classList.toggle` **BUT** the second boolean parameter isn't supported in IE / Opera 12-

If you swap out `this.classList.toggle()` with the utility function Polymer provides for the same purpose: `this.toggleClass()`, everything works fine. 

I'm going to submit a pull request.

**Comment by L-u-k-e** [comment] 2016-01-23 13:37
My pull request was merged with `paper-behaviors`.

So, this can be closed now.

**Closed** 2016-01-25 15:24 UTC
